name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl pandas
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "ExcelConverter" excel_reader.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ExcelConverter-Windows
        path: dist/ExcelConverter.exe
  
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl pandas
    
    - name: Build with PyInstaller (macOS - onedir mode)
      run: |
        pyinstaller --onedir --windowed --name "ExcelConverter" excel_reader.py
    
    - name: Create DMG (optional)
      run: |
        brew install create-dmg
        create-dmg \
          --volname "ExcelConverter" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --app-drop-link 450 185 \
          "ExcelConverter.dmg" \
          "dist/ExcelConverter.app" || true
    
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: ExcelConverter-macOS
        path: |
          dist/ExcelConverter.app
          ExcelConverter.dmg