name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl pandas
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "ExcelConverter" --clean -y excel_reader.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ExcelConverter-Windows
        path: dist/ExcelConverter.exe
  
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl pandas
    
    - name: Clean previous builds
      run: |
        rm -rf build dist *.spec
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onedir --windowed --name "ExcelConverter" --clean -y excel_reader.py
    
    - name: Zip macOS app
      run: |
        cd dist
        zip -r ExcelConverter-macOS.zip ExcelConverter.app
    
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: ExcelConverter-macOS
        path: dist/ExcelConverter-macOS.zip